### PR TITLE
(hot_fix.sh) Remove force option.

### PR DESCRIPTION
**Pull request by 130s**
Discussed in https://github.com/tork-a/88_tools/issues/4#issuecomment-90988441

Below is the outputs from what I tested both `-fN` and `-N` respectively, where the patch is already applied and thus the patch command should fail.

The difference of the output is not that clear to me, but maybe `-N` might be more user-friendly. Moreover, NOT forcing the user to go ahead is in general a good idea.

I ask @k-okada for the decision if we merge this PR or not.

```
$ ./hot_fix.sh start-jsk/rtmros_hironx 351 /opt/ros/hydro/lib/python2.7/dist-packages/hironx_ros_bridge 4
;; download patch file https://github.com/start-jsk/rtmros_hironx/pull/351.diff

diff --git a/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py b/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py
:
sudo patch -fN -p3 < /tmp/14261.patch
patching file hironx_ros_bridge/hironx_client.py
Hunk #1 succeeded at 46 with fuzz 2 (offset -7 lines).
Hunk #2 FAILED at 152.
Hunk #3 FAILED at 648.
Hunk #4 FAILED at 679.
3 out of 4 hunks FAILED -- saving rejects to file hironx_ros_bridge/hironx_client.py.rej
The next patch would create the file hironx_ros_bridge/hrpsys_315_1_9/hrpsys/ImpedanceControllerService_idl.py,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file hironx_ros_bridge/hrpsys_315_1_9/hrpsys/__init__.py,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
patching file hironx_ros_bridge/hironx_client.py
patching file hironx_ros_bridge/hrpsys_315_1_9/hrpsys/ImpedanceControllerService_idl.py
patching file hironx_ros_bridge/hrpsys_315_1_9/hrpsys/__init__.py
This patch is already applied
```

```
$ ./hot_fix.sh start-jsk/rtmros_hironx 351 /opt/ros/hydro/lib/python2.7/dist-packages/hironx_ros_bridge 4
;; download patch file https://github.com/start-jsk/rtmros_hironx/pull/351.diff

diff --git a/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py b/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py
index dbd0426..cab796d 100644
--- a/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py
+++ b/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py
:
sudo patch -N -p3 < /tmp/14279.patch
patching file hironx_ros_bridge/hironx_client.py
Reversed (or previously applied) patch detected!  Skipping patch.
4 out of 4 hunks ignored -- saving rejects to file hironx_ros_bridge/hironx_client.py.rej
The next patch would create the file hironx_ros_bridge/hrpsys_315_1_9/hrpsys/ImpedanceControllerService_idl.py,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file hironx_ros_bridge/hrpsys_315_1_9/hrpsys/__init__.py,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
patching file hironx_ros_bridge/hironx_client.py
patching file hironx_ros_bridge/hrpsys_315_1_9/hrpsys/ImpedanceControllerService_idl.py
patching file hironx_ros_bridge/hrpsys_315_1_9/hrpsys/__init__.py
This patch is already applied
```

### CODE REVIEW

**Comment by k-okada** [comment]
I think this is nice, one big problem of this approach is that we do not 
know whether if we already applied the patch of not
One idea is to force change <version> of package.xml such as 0.0.1-patch222 
and it seems ok, but some of ros tools strictly checks
version format.
so usually we forget that we already applied patch and there are no mean of 
tell that, so this is more informative
Another solution is put some files under the some directly to keep track if 
patches we applied.

## 

◉ Kei Okada

**Comment by 130s** [comment]
Maybe I don't fully support this date PR of my own. Without `-f`, `patch` starts asking a quesiton that I have no idea.

```
./hot_fix.sh fkanehiro/hrpsys-base 978 /opt/ros/indigo/lib/python2.7/dist-packages/hrpsys 0
:
File to patch: 
```

Here I'm asked to respond, but I have no idea what to type in.

**Comment by 130s** [comment]
Maybe I don't fully support this dated PR of my own. Without `-f`, `patch` starts asking a quesiton that I have no idea.

```
./hot_fix.sh fkanehiro/hrpsys-base 978 /opt/ros/indigo/lib/python2.7/dist-packages/hrpsys 0
:
File to patch: 
```

Here I'm asked to respond, but I have no idea what to type in.

**Comment by k-okada** [comment]
i see, how about `./hot_fix.sh fkanehiro/hrpsys-base 983
/opt/ros/indigo/lib/python2.7/dist-packages/hrpsys 2`

## 

◉ Kei Okada

**Comment by 130s** [comment]
Discussion moved to https://github.com/tork-a/88_tools/issues/12

**Pull request closed without merging**
